version: '3.9'

services:

  postgres:
    image: postgres:16.3
    restart: "no"
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: