version: '3.9'

services:

  postgres:
    image: postgres:15.1
    restart: always
    env_file:
      - ./.env.prod
    expose:
      - "5432"
    volumes:
      - ./service-postgres/data:/var/lib/postgresql/data
      - ./service-postgres/sql:/docker-entrypoint-initdb.d

  flask:
    build: ./service-flask
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    expose:
      - "5000"
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/usr/src/app/voluntariat_app/static
    depends_on:
      - postgres

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./service-nginx:/etc/nginx/conf.d
      - static_volume:/usr/src/app/voluntariat_app/static
    depends_on:
      - flask

volumes:
  # d'aquesta manera nginx serveix el contingut estàtic, alliberant flask
  static_volume: