version: '3.9'

services:

  postgres:
    image: postgres:15.2
    restart: "no"
    environment:
      POSTGRES_PASSWORD: demo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./service-postgres/data:/var/lib/postgresql/data
      - ./service-postgres/sql:/docker-entrypoint-initdb.d