version: '3.9'

services:

  postgres:
    image: postgres:15.3
    restart: "no"
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./service-postgres/data:/var/lib/postgresql/data
      - ./service-postgres/sql:/docker-entrypoint-initdb.d