version: '3.9'

services:

  postgres:
    image: postgres:16.1
    restart: no
    env_file:
      - ./.env.development
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data
      
  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    env_file:
      - ./.env.development
    volumes:
      - .:/usr/src/flask
      - ./.env.development:/usr/src/flask/.env # m'asseguro que el .env.production es el que s'usa
    depends_on:
      - postgres

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./nginx/conf-development:/etc/nginx/conf.d
      - ./voluntariat_app/static:/static
    depends_on:
      - flask

volumes:
  postgres_volume: